# Generated by Selenium IDE
import pytest
from model.group import Group
from fixture.application import Application

@pytest.fixture
def app(request):
    firxture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture

    def test_login2(app):
    app.login(Group (username="annaTest50", password="annaTest50"))
    app.logout()

    def logout(app):
    app.driver.execute_script("window.scrollTo(0,0)")
    app.driver.find_element(By.CSS_SELECTOR, ".client-section-menu__caret-down-icon > .icons-font-caret-down").click()
    app.driver.find_element(By.CSS_SELECTOR, ".btn-signout__title").click()



  
