# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from group import Group


class TestLogin():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def test_login(self):
    self.open_login_form()
    self.fill_in_login_form(Group (username="annaTest50", password = "annaTest50"))
    self.logout()

  def teardown_method(self, method):
    self.driver.quit()
  


  def logout(self):
    # 11 | runScript | window.scrollTo(0,0) |  |
    self.driver.execute_script("window.scrollTo(0,0)")
    # 12 | click | css=.client-section-menu__account-logo |  |
    self.driver.find_element(By.CSS_SELECTOR, ".client-section-menu__account-logo").click()
    # 13 | click | css=.client-section-menu__btn-signout |  |
    self.driver.find_element(By.CSS_SELECTOR, ".client-section-menu__btn-signout").click()

  def fill_in_login_form(self, group):
    # 3 | runScript | window.scrollTo(0,0) |  |
    self.driver.execute_script("window.scrollTo(0,0)")
    # 4 | click | css=.auth-controls__btn_login .auth-controls__title |  |
    self.driver.find_element(By.CSS_SELECTOR, ".auth-controls__btn_login .auth-controls__title").click()
    # 5 | click | css=.user-credentials-form__item:nth-child(1) .ng-untouched |  |
    self.driver.find_element(By.CSS_SELECTOR, ".user-credentials-form__item:nth-child(1) .ng-untouched").click()
    # 6 | type | css=.ng-valid | annaTest50 |
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys(group.username)
    # 7 | click | css=.ng-untouched |  |
    self.driver.find_element(By.CSS_SELECTOR, ".ng-untouched").click()
    # 8 | type | css=.ng-untouched | annaTest50 |
    self.driver.find_element(By.CSS_SELECTOR, ".ng-untouched").send_keys(group.password)
    # 9 | click | css=.user-credentials-form |  |
    self.driver.find_element(By.CSS_SELECTOR, ".user-credentials-form").click()
    # 10 | click | css=.user-credentials-form__btn |  |
    self.driver.find_element(By.CSS_SELECTOR, ".user-credentials-form__btn").click()

  def open_login_form(self):
    # 1 | open | /en/casino/list/all-games |  |
    self.driver.get("https://platform.today/en/casino/list/all-games")
    # 2 | setWindowSize | 1265x1080 |  |
    self.driver.set_window_size(1265, 1080)
  
